### ISSUE TITLE
Build site github action not working

### ISSUE THREAD

**Issue by garrettgalow** [cloudflare/api-docs#32]

**Comment by garrettgalow** [comment]
link to latest log: https://github.com/cloudflare/api-docs/runs/575271515?check_suite_focus=true

```  
##[error]Process completed with exit code 1.
Run wrangler build
  wrangler build
  shell: /bin/bash -e {0}
Error: You must specify either `workers_dev` or `route` and `zone_id` in order to publish.
##[error]Process completed with exit code 1. 
```

@victoriabernard92 should I just remove this altogether since it seems like this steps wants to publish the script somewhere? I suppose maybe I could have it deploy to some worker.dev instance...

**Comment by victoriabernard92** [comment]
@garrettgalow Yes, in your wrangler.toml you want either workers_dev or route set not both. So set `workers_dev = false`
